app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

  support:
    url: https://github.com/polarpoint-io/backstage/issues # Used by common ErrorPage
    items: # Used by common SupportButton component
      - title: Issues
        icon: github
        links:
          - url: https://github.com/backstage/backstage/issues
            title: GitHub Issues
      - title: Slack Chatroom
        icon: chat
        links:
          - url: https://polarpoint.slack.com/archives/C03T35W09HC
            title: '#backstage'

organization:
  name: Polarpoint

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/tutorials/backend-to-backend-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", 'data:', 'https://avatars.githubusercontent.com']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir


integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: ${K8S_URL}
          name: development
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: ${K8S_TOKEN}

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local or docker'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

# techdocs:
#   publisher:
#     type: 'awsS3'
#     awsS3:
#       bucketName: 'name-of-techdocs-storage-bucket'
#       region: ${AWS_REGION}
#       credentials:
#         accessKeyId: ${AWS_ACCESS_KEY_ID}
#         secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

proxy:
  '/sonarqube':
    target: http://sonar.sonar.svc/api
    allowedMethods: ['GET']
    # note that the colon after the token is required
    auth: '${SONARQUBE_TOKEN}:'
    # Environmental variable: SONARQUBE_TOKEN
    # Fetch the sonar-auth-token from https://sonarcloud.io/account/security/

  '/argocd/api':
    target: http://argocd-server.argocd.svc/api/v1/
    changeOrigin: true
    # only if your argocd api has self-signed cert
    secure: true
    headers:
      Cookie:
        $env: ARGOCD_AUTH_TOKEN

  '/grafana/api':
    # May be an internal DNS
    target: http://grafana.monitoring.svc:3000/
    headers:
      Authorization: Bearer ${GRAFANA_TOKEN}

  '/prometheus/api':
    # url to the api and path of your hosted prometheus instance
    target: http://prometheus.monitoring.svc:9090/api/v1/


sonarQube:
  baseUrl: https://code-analysis.polarpoint.io

grafana:
  domain: https://dashboard.polarpoint.io

# auth:
#   # see https://backstage.io/docs/auth/ to learn about auth providers
#   providers: {}

auth:
  environment: development
  ### Providing an auth.session.secret will enable session support in the auth-backend
  # session:
  #   secret: custom session secret
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options
  defaultAuthor:
    name: ':robot: [backstage-bot]'
    email: mail@polarpoint.io
  # defaultCommitMessage: "🤖 U can't touch this" # Defaults to 'Initial commit'

# Force Deploy

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - API
        - Component
        - Domain
        - Group
        - System
        - User
        - Template
        - Resource
        - Location

  locations:
    # Backstage example components
    - type: url
      target: https://github.com/polarpoint-io/backstage-catalog/blob/main/polarpoint-io/all.yaml


